### ISSUE TITLE
issues with alarm program

### ISSUE THREAD

**Issue by KewTeacher** [mikkiduan/Mikkichapter2-4#1]
Hi Micci,
I ran your alarm program and found a couple errors:
The first line needs to be commented out. It should start with a `#`

Here's your code:
```
timenow = float(input("what time is it now 0-24"))
hourswait = float(input("How many hours are you waiting?"))

alarttime = hourwait % 24 + timenow
print("your alarm will go off at: " + str(alarmtime))
```

Look closely at `hourswait` in line 5 you have `hourwait`
please revise

**Comment by mikkiduan** [comment]
I fixed it. tested it.

Thanks

**Comment by KewTeacher** [comment]
great!
